# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

port: 5000

# Site settings
title: Yijun Tian
email: meettianyijun@gmail.com
description:  # this means to ignore newlines until "baseurl:"
# this will appear in your document head meta (for  Google search results) and in your feed.xml site description.
  think and code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/meettyj/blog" # the base hostname & protocol for your site
twitter_username:  
github_username:  meettyj 

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
